---

- hosts: all
  become: true

  tasks:
  - name: install apache2 and php package for Ubuntu Servers
    apt:
      name: 
        - apache2
        - ilbapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install httpd and php package for CentOS servers
    package:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == ["Rocky", "OracleLinux"]
