---

- hosts: all
  become: true

  tasks:
    - name: install apache2 package
      yum:
        name: httpd
        state: latest
    - name: add php support for apache
      yum:
        name: php
        state: latest
