  - name: install apache2 and php package for Ubuntu Servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install httpd and php package for CentOS servers
    tags: apache,centos,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Rocky" or ansible_distribution == "OracleLinux"

  - name: start httpd (CentOS)
    tags: apache,httpd,centos
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "Rocky" or ansible_distribution == "OracleLinux"

  - name: change email address for admin
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "Rocky" or ansible_distribution == "OracleLinux"
    register: httpd

  - name: restart httpd ( CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_sites.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
