  - name : install mariadb package (CentOS)
    tags: centos,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "Rocky" or ansible_distribution == "OracleLinux"

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: maiadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
